#!/usr/bin/env bash
# Transfers a file from client to specified server
if [ "$#" -lt 3 ]
then
	echo "Usage: $(basename "$0") PATH_TO_FILE IP USERNAME \
PATH_TO_SSH_KEY"
	exit
fi

scp -i "$4" "$1" "$3"@"$2":~/
exit
