#!/usr/bin/env bash
# Installs nginx web server and configures it

apt-get -y update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

mkdir -p /etc/nginx/sites-enabled/ 
echo -e "server {\
	listen 80 default_server;\
	listen [::]:80 default_server;\
	root /var/www/html;\
	index index.html index.htm index.nginx-debian.html;\
	server_name _;\
	location / {\
		try_files \$uri \$uri/ =404;\
	}\
}" > /etc/nginx/sites-enabled/default

mkdir -p /var/www/html/
echo -e "Hello World!" > /var/www/html/index.html

run_at_port=$(lsof -i :80 | \
sed -n '2{s/^[[:space:]]*\([^[:space:]]*\).*/\1/p}')
if [ -n "$run_at_port" ]
then
	pkill "$run_at_port"
fi
nginx
exit
