#!/usr/bin/env bash
# Installs nginx web server and configures it

apt-get -y update
apt-get -y install curl gnupg2 ca-certificates lsb-release ubuntu-keyring

curl https://nginx.org/keys/nginx_signing.key | gpg --dearmor \
| sudo tee /usr/share/keyrings/nginx-archive-keyring.gpg >/dev/null

known_hash=573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62
signed_hash=$(gpg --dry-run --quiet --no-keyring --import --import-options \
import-show /usr/share/keyrings/nginx-archive-keyring.gpg | sed -n \
'2{s/[[:space:]]//g;p}')
if [ "$signed_hash" != "$known_hash" ]
then
	rm /usr/share/keyrings/nginx-archive-keyring.gpg
	exit
fi

echo "deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] \
http://nginx.org/packages/ubuntu $(lsb_release -cs) nginx" \
| tee /etc/apt/sources.list.d/nginx.list

echo -e "Package: *\nPin: origin nginx.org\nPin: release o=nginx\nPin-Priority: 900\n" \
| tee /etc/apt/preferences.d/99nginx

apt-get -y update
apt-get -y install nginx

ufw allow 'Nginx HTTP'

mkdir -p /etc/nginx/sites-enabled/ 
echo -e "server {\
	listen 80 default_server;\
	listen [::]:80 default_server;\
	root /var/www/html;\
	index index.html index.htm index.nginx-debian.html;\
	server_name _;\
	location / {\
		try_files \$uri \$uri/ =404;\
	}\
}" > /etc/nginx/sites-enabled/default

mkdir -p /var/www/html/
echo -e "Hello World!\n" > /var/www/html/index.html

run_at_port=$(lsof -i :80 | \
sed -n '2{s/^[[:space:]]*\([^[:space:]]*\).*/\1/p}')
if [ -n "$run_at_port" ]
then
	pkill "$run_at_port"
fi
nginx
exit
