#!/usr/bin/env bash
# Installs nginx web server and configures it

mkdir -p /etc/nginx/sites-enabled/
add_val="error_page 404 /404-def.html;\n\
	location = /404-def.html {\n\
		root /var/www/html;\n\
		internal;\n\
	}"
echo -e "server {\n\
	listen 80 default_server;\n\
	listen [::]:80 default_server;\n\
	root /var/www/html;\n\
	index index.html index.htm index.nginx-debian.html;\n\
	server_name _;\n\
	location / {\n\
		try_files \$uri \$uri/ =404;\n\
	}\n\
	$add_val
}" > /etc/nginx/sites-enabled/default

mkdir -p /var/www/html/
echo -e "Ceci n'est pas une page\n" > /var/www/html/404.html

run_at_port=$(lsof -i :80 | \
sed -n '2{s/^[[:space:]]*\([^[:space:]]*\).*/\1/p}')
if [ -n "$run_at_port" ]
then
	pkill "$run_at_port"
fi
nginx
exit
