#!/usr/bin/env bash
# Install HAProxy
apt-get install --y --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0
apt-get -y install haproxy=2.0.\*
sudo tee /etc/haproxy/haproxy.cfg >/dev/null <<EOL
global
    log /dev/log    local0
    log /dev/log    local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client 50000
    timeout server 50000

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server server1 54.237.61.71:80 check
    server server2 54.146.64.127:80 check
EOL

sudo systemctl enable haproxy
sudo systemctl restart haproxy
