#!/usr/bin/env bash
# Printing "Best School" 10 times

n=1
while [ "$n" -le 20 ]
do
    case $n in
    4)
        echo "bad luck from China";;
    9)
        echo "bad luck from Japan";;
    17)
        echo "bad luck from Italy";;
    esac
    echo $n
    n=$((n + 1))
done
