#!/usr/bin/env bash
# Printing "Best School" 10 times

n=0
while [ "$n" -lt 20 ]
do
    case $n in
    4)
        echo "bad luck from China";;
    9)
        echo "bad luck from Japan";;
    17)
        echo "bad luck from Italy";;
    esac
    echo $((n + 1))
    n=$((n + 1))
done
