#!/usr/bin/env bash
# Run nginx as nginx user

sudo pkill nginx
sudo sed -i 's/^user [^ ]*$/user nginx/' /etc/nginx/nginx.conf
sudo sed -i 's/[[:space:]listen[[:space:]]\+80;$/\tlisten\t 8080;/' \
/etc/nginx/conf.d/default.conf
sudo chown -R nginx:nginx /etc/nginx/
sudo usermod -aG root nginx
servive nginx restart
